"""Script d'initialisation des configurations pays par défaut"""

PAYS_DEFAUT = [
    {
        "code_pays": "BFA",
        "nom_pays": "Burkina Faso",
        "nom_pays_en": "Burkina Faso",
        "continent": "Afrique",
        "region": "Afrique de l'Ouest",
        "systeme_educatif": "LMD",
        "organisme_regulation": "CAMES",
        "langue_officielle": "Français",
        "langues_secondaires": '["Mooré", "Dioula", "Fulfuldé"]',
        "devise_officielle": "XOF",
        "symbole_devise": "FCFA",
        "format_montant": "#,##0",
        "format_telephone": "^\\+226[0-9]{8}$",
        "format_code_postal": "",
        "format_matricule": "BFA-{ANNEE}-{SEQUENCE}",
        "systeme_notation_defaut": "20",
        "note_min_defaut": 0,
        "note_max_defaut": 20,
        "fuseau_horaire": "Africa/Ouagadougou",
        "format_date_defaut": "DD/MM/YYYY",
        "debut_annee_academique": "10-01",
        "fin_annee_academique": "09-30",
        "jours_feries": '["01-01", "01-03", "05-01", "08-05", "08-15", "11-01", "12-11", "12-25"]',
        "indicatif_telephonique": "+226"
    },
    {
        "code_pays": "CIV",
        "nom_pays": "Côte d'Ivoire",
        "nom_pays_en": "Ivory Coast",
        "continent": "Afrique",
        "region": "Afrique de l'Ouest",
        "systeme_educatif": "LMD",
        "organisme_regulation": "CAMES",
        "langue_officielle": "Français",
        "langues_secondaires": '["Baoulé", "Dioula", "Bété"]',
        "devise_officielle": "XOF",
        "symbole_devise": "FCFA",
        "format_montant": "#,##0",
        "format_telephone": "^\\+225[0-9]{10}$",
        "format_code_postal": "",
        "format_matricule": "CIV-{ANNEE}-{SEQUENCE}",
        "systeme_notation_defaut": "20",
        "note_min_defaut": 0,
        "note_max_defaut": 20,
        "fuseau_horaire": "Africa/Abidjan",
        "format_date_defaut": "DD/MM/YYYY",
        "debut_annee_academique": "10-01",
        "fin_annee_academique": "09-30",
        "jours_feries": '["01-01", "05-01", "08-07", "08-15", "11-01", "11-15", "12-25"]',
        "indicatif_telephonique": "+225"
    },
    {
        "code_pays": "SEN",
        "nom_pays": "Sénégal",
        "nom_pays_en": "Senegal",
        "continent": "Afrique",
        "region": "Afrique de l'Ouest",
        "systeme_educatif": "LMD",
        "organisme_regulation": "CAMES",
        "langue_officielle": "Français",
        "langues_secondaires": '["Wolof", "Sérère", "Peul"]',
        "devise_officielle": "XOF",
        "symbole_devise": "FCFA",
        "format_montant": "#,##0",
        "format_telephone": "^\\+221[0-9]{9}$",
        "format_code_postal": "",
        "format_matricule": "SEN-{ANNEE}-{SEQUENCE}",
        "systeme_notation_defaut": "20",
        "note_min_defaut": 0,
        "note_max_defaut": 20,
        "fuseau_horaire": "Africa/Dakar",
        "format_date_defaut": "DD/MM/YYYY",
        "debut_annee_academique": "10-01",
        "fin_annee_academique": "09-30",
        "jours_feries": '["01-01", "04-04", "05-01", "08-15", "11-01", "12-25"]',
        "indicatif_telephonique": "+221"
    },
    {
        "code_pays": "MLI",
        "nom_pays": "Mali",
        "nom_pays_en": "Mali",
        "continent": "Afrique",
        "region": "Afrique de l'Ouest",
        "systeme_educatif": "LMD",
        "organisme_regulation": "CAMES",
        "langue_officielle": "Français",
        "langues_secondaires": '["Bambara", "Peul", "Songhaï"]',
        "devise_officielle": "XOF",
        "symbole_devise": "FCFA",
        "format_montant": "#,##0",
        "format_telephone": "^\\+223[0-9]{8}$",
        "format_code_postal": "",
        "format_matricule": "MLI-{ANNEE}-{SEQUENCE}",
        "systeme_notation_defaut": "20",
        "note_min_defaut": 0,
        "note_max_defaut": 20,
        "fuseau_horaire": "Africa/Bamako",
        "format_date_defaut": "DD/MM/YYYY",
        "debut_annee_academique": "10-01",
        "fin_annee_academique": "09-30",
        "jours_feries": '["01-01", "01-20", "05-01", "05-25", "09-22", "12-25"]',
        "indicatif_telephonique": "+223"
    },
    {
        "code_pays": "NER",
        "nom_pays": "Niger",
        "nom_pays_en": "Niger",
        "continent": "Afrique",
        "region": "Afrique de l'Ouest",
        "systeme_educatif": "LMD",
        "organisme_regulation": "CAMES",
        "langue_officielle": "Français",
        "langues_secondaires": '["Haoussa", "Zarma", "Tamashek"]',
        "devise_officielle": "XOF",
        "symbole_devise": "FCFA",
        "format_montant": "#,##0",
        "format_telephone": "^\\+227[0-9]{8}$",
        "format_code_postal": "",
        "format_matricule": "NER-{ANNEE}-{SEQUENCE}",
        "systeme_notation_defaut": "20",
        "note_min_defaut": 0,
        "note_max_defaut": 20,
        "fuseau_horaire": "Africa/Niamey",
        "format_date_defaut": "DD/MM/YYYY",
        "debut_annee_academique": "10-01",
        "fin_annee_academique": "09-30",
        "jours_feries": '["01-01", "04-24", "05-01", "08-03", "12-18", "12-25"]',
        "indicatif_telephonique": "+227"
    },
    {
        "code_pays": "TGO",
        "nom_pays": "Togo",
        "nom_pays_en": "Togo",
        "continent": "Afrique",
        "region": "Afrique de l'Ouest",
        "systeme_educatif": "LMD",
        "organisme_regulation": "CAMES",
        "langue_officielle": "Français",
        "langues_secondaires": '["Éwé", "Kabyè"]',
        "devise_officielle": "XOF",
        "symbole_devise": "FCFA",
        "format_montant": "#,##0",
        "format_telephone": "^\\+228[0-9]{8}$",
        "format_code_postal": "",
        "format_matricule": "TGO-{ANNEE}-{SEQUENCE}",
        "systeme_notation_defaut": "20",
        "note_min_defaut": 0,
        "note_max_defaut": 20,
        "fuseau_horaire": "Africa/Lome",
        "format_date_defaut": "DD/MM/YYYY",
        "debut_annee_academique": "10-01",
        "fin_annee_academique": "09-30",
        "jours_feries": '["01-01", "01-13", "04-27", "05-01", "06-21", "08-15", "11-01", "12-25"]',
        "indicatif_telephonique": "+228"
    },
    {
        "code_pays": "BEN",
        "nom_pays": "Bénin",
        "nom_pays_en": "Benin",
        "continent": "Afrique",
        "region": "Afrique de l'Ouest",
        "systeme_educatif": "LMD",
        "organisme_regulation": "CAMES",
        "langue_officielle": "Français",
        "langues_secondaires": '["Fon", "Yoruba", "Bariba"]',
        "devise_officielle": "XOF",
        "symbole_devise": "FCFA",
        "format_montant": "#,##0",
        "format_telephone": "^\\+229[0-9]{8}$",
        "format_code_postal": "",
        "format_matricule": "BEN-{ANNEE}-{SEQUENCE}",
        "systeme_notation_defaut": "20",
        "note_min_defaut": 0,
        "note_max_defaut": 20,
        "fuseau_horaire": "Africa/Porto-Novo",
        "format_date_defaut": "DD/MM/YYYY",
        "debut_annee_academique": "10-01",
        "fin_annee_academique": "09-30",
        "jours_feries": '["01-01", "01-10", "05-01", "08-01", "08-15", "11-01", "11-30", "12-25"]',
        "indicatif_telephonique": "+229"
    },
    {
        "code_pays": "CMR",
        "nom_pays": "Cameroun",
        "nom_pays_en": "Cameroon",
        "continent": "Afrique",
        "region": "Afrique Centrale",
        "systeme_educatif": "LMD",
        "organisme_regulation": "CAMES",
        "langue_officielle": "Français",
        "langues_secondaires": '["Anglais", "Ewondo", "Douala"]',
        "devise_officielle": "XAF",
        "symbole_devise": "FCFA",
        "format_montant": "#,##0",
        "format_telephone": "^\\+237[0-9]{9}$",
        "format_code_postal": "",
        "format_matricule": "CMR-{ANNEE}-{SEQUENCE}",
        "systeme_notation_defaut": "20",
        "note_min_defaut": 0,
        "note_max_defaut": 20,
        "fuseau_horaire": "Africa/Douala",
        "format_date_defaut": "DD/MM/YYYY",
        "debut_annee_academique": "09-01",
        "fin_annee_academique": "08-31",
        "jours_feries": '["01-01", "02-11", "05-01", "05-20", "08-15", "12-25"]',
        "indicatif_telephonique": "+237"
    },
    {
        "code_pays": "GAB",
        "nom_pays": "Gabon",
        "nom_pays_en": "Gabon",
        "continent": "Afrique",
        "region": "Afrique Centrale",
        "systeme_educatif": "LMD",
        "organisme_regulation": "CAMES",
        "langue_officielle": "Français",
        "langues_secondaires": '["Fang", "Myene", "Nzebi"]',
        "devise_officielle": "XAF",
        "symbole_devise": "FCFA",
        "format_montant": "#,##0",
        "format_telephone": "^\\+241[0-9]{8}$",
        "format_code_postal": "",
        "format_matricule": "GAB-{ANNEE}-{SEQUENCE}",
        "systeme_notation_defaut": "20",
        "note_min_defaut": 0,
        "note_max_defaut": 20,
        "fuseau_horaire": "Africa/Libreville",
        "format_date_defaut": "DD/MM/YYYY",
        "debut_annee_academique": "09-01",
        "fin_annee_academique": "08-31",
        "jours_feries": '["01-01", "03-12", "05-01", "08-15", "08-17", "11-01", "12-25"]',
        "indicatif_telephonique": "+241"
    },
    {
        "code_pays": "COD",
        "nom_pays": "République Démocratique du Congo",
        "nom_pays_en": "Democratic Republic of the Congo",
        "continent": "Afrique",
        "region": "Afrique Centrale",
        "systeme_educatif": "LMD",
        "organisme_regulation": "CAMES",
        "langue_officielle": "Français",
        "langues_secondaires": '["Lingala", "Swahili", "Kikongo", "Tshiluba"]',
        "devise_officielle": "CDF",
        "symbole_devise": "FC",
        "format_montant": "#,##0",
        "format_telephone": "^\\+243[0-9]{9}$",
        "format_code_postal": "",
        "format_matricule": "COD-{ANNEE}-{SEQUENCE}",
        "systeme_notation_defaut": "20",
        "note_min_defaut": 0,
        "note_max_defaut": 20,
        "fuseau_horaire": "Africa/Kinshasa",
        "format_date_defaut": "DD/MM/YYYY",
        "debut_annee_academique": "09-01",
        "fin_annee_academique": "08-31",
        "jours_feries": '["01-01", "01-04", "05-01", "05-17", "06-30", "08-01", "12-25"]',
        "indicatif_telephonique": "+243"
    }
]


def init_pays(db):
    """Initialise les configurations pays par défaut"""
    from app.models.pays_configuration import PaysConfiguration
    from decimal import Decimal
    
    count = 0
    for pays_data in PAYS_DEFAUT:
        existing = db.query(PaysConfiguration).filter(
            PaysConfiguration.code_pays == pays_data["code_pays"]
        ).first()
        
        if not existing:
            pays_data["note_min_defaut"] = Decimal(str(pays_data["note_min_defaut"]))
            pays_data["note_max_defaut"] = Decimal(str(pays_data["note_max_defaut"]))
            pays = PaysConfiguration(**pays_data)
            db.add(pays)
            count += 1
    
    db.commit()
    return count
